name: Generate documentations
on:
  push:
  workflow_dispatch:

jobs:
  GenerateDocumentation:
    if: github.repository_owner == 'AuroraEditor'
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: Update documentation
        run: swift application.swift

      - name: Upload documentation to repo
        # if: github.event.pull_request.merged == true
        run: |
          git config --global user.name 'aurora-care-bear'
          git config --global user.email 'aurora-care-bear@users.noreply.github.com'
          git remote set-url --push origin https://aurora-care-bear:$BOT_TOKEN@github.com/AuroraEditor/AEExtensionKit-Documentation
          git add -a docs
          git commit -m "Update Cdocumentation"
          git push origin HEAD:main
